class ProductController{
    constructor($stateParams){
        var details = [
            {id: 1,
            rank: "#1",     
            name: "Suicide Squad",  
            info: "Anticipation was high for the first big-budget movie lead by supervillains. All the signs were good with a cast that included Will Smith as Deadshot, Jared Leto as the Joker and Margot Robbie as the baseball bat-wielding troublemaker Harley Quinn. Robbie stole the show and the film helped position her as IMDb’s top star of 2016. And while there were naysayers for the film, written and directed by David Ayer, Suicide Squad took more than $745 million at the worldwide box office and made it the most popular movie on IMDb in 2016.", pic:"https://images-na.ssl-images-amazon.com/images/M/MV5BNzM5MjczODA1NV5BMl5BanBnXkFtZTgwODUxNzA0OTE@._V1_UY666_CR166,0,666,666_AL_.jpg",
            pic2:"https://events.ucsb.edu/wp-content/uploads/2016/09/Suicide-Squad.jpg",
            pic3:"http://www.dccomics.com/sites/default/files/styles/recent_activity_lrg_horizontal/public/field/image/DCAAGiveaway_12-13_584f76163a2337.26517104.jpg?itok=gMr4DCDw"},    
            {id: 2,
            rank: "#2",     
            name: "Captain America: Civil War ",  
            info: "It may have said Captain America on the label but this was an Avengers movie and one that many felt was more satisfying that last year’s Avengers: Age of Ultron. Rather than destroying cities with a CGI menace, the film centered on one man taking revenge on Earth’s mightiest heroes by pitting them against each other. The film, which topped this year’s worldwide box office with $1.15 billion, also introduced Black Panther, who will be the focus of his own standalone movie in 2018.",  
            pic:"https://images-na.ssl-images-amazon.com/images/M/MV5BODg3OTc4MTEyMl5BMl5BanBnXkFtZTgwODI0MDkyODE@._V1_UY666_CR301,0,666,666_AL_.jpg",
            pic2:"https://upload.wikimedia.org/wikipedia/en/5/53/Captain_America_Civil_War_poster.jpg",
            pic3:"http://cdn.bloody-disgusting.com/wp-content/uploads/2016/07/Civil-War-2.jpg"},
            {id: 3, 
            rank: "#3",
            name: "Batman v Superman: Dawn of Justice",  
            info: "It was the showdown that comic book fans had waited decades to see on the big screen. But as the two men wrestled with mommy issues, the real star of the show was Wonder Woman – one of several superheroes introduced by the movie to jumpstart DC’s cinematic universe. A critical kicking did not stop the movie from taking more than $873 million at the worldwide box office.",  
            pic:"https://images-na.ssl-images-amazon.com/images/M/MV5BMjI5MjM4MzM1NV5BMl5BanBnXkFtZTgwNzA5MjkxNjE@._V1_UY666_CR331,0,666,666_AL_.jpg",
            pic2:"http://www.mediastinger.com/wp-content/uploads/2016/01/Batman-v-Superman-Dawn-of-Justice-2016-after-credits-hq.jpg",
            pic3:"http://www.avsforum.com/wordpress/wp-content/uploads/2016/07/Batman-V-Superman-Dawn-of-Justice.jpg"},
            {id: 4,
            rank: "#4",
            name: "Deadpool",
            info: "This R-rated superhero movie, packed with sex and violence, shook up the genre and proved a massive, breakout hit, due in part to a wildly inventive marketing campaign. Not only did it take nearly $783 million at the worldwide box office, it has also been nominated for two Golden Globes including best actor for Ryan Reynolds. At time of writing, Deadpool had the highest IMDb rating of this list, scoring 8.1 out of 10. A sequel is due in 2018.",  
            pic:"http://is1.mzstatic.com/image/thumb/Video4/v4/69/97/72/69977202-baa8-227d-26eb-18eddcc6c3f2/source/1200x630bb.jpg",
            pic2:"http://nerdist.com/wp-content/uploads/2016/04/deadpool-2-featured-image.jpg",
            pic3:"https://www.sideshowtoy.com/wp-content/uploads/2016/01/marvel-deadpool-sixth-scale-hot-toys-feature-902628.jpg"},
            {id: 5, 
            rank: "#5",
            name: "X-Men: Apocalypse",
            info: "The ninth installment in the X-Men franchise saw the return of an all-star cast including James McAvoy, Michael Fassbender and Jennifer Lawrence. This time, the mutants were up against supervillain Apocalypse, played by a barely recognizable Oscar Isaac buried under a ton of blue make-up. While poorly received by critics, worldwide box office of nearly $544 million has talk of a follow-up well underway.", 
            pic:"https://images-na.ssl-images-amazon.com/images/M/MV5BMjMxODIxNTIwNV5BMl5BanBnXkFtZTgwOTk0MTY0NzE@._V1_UY666_CR298,0,666,666_AL_.jpg",
            pic2:"https://i.ytimg.com/vi/Hm8mcUMmHxQ/maxresdefault.jpg",
            pic3:"https://upload.wikimedia.org/wikipedia/en/0/04/X-Men_-_Apocalypse.jpg"},
            {id: 6,
            rank: "#6",
            name: "The Jungle Book",
            info: "Doubts were raised when Disney announced it was making a live-action version of its beloved animated classic, The Jungle Book. But those fears faded fast when the results were seen. The fact that Neel Sethi, as young Mowgli, was the only real thing in a CG jungle populated with CG animals was almost hard to believe, such was the level of reality achieved by those artists. And after launching the current wave of superhero movies with Iron Man, director Jon Favreau has now buoyed Disney’s live-action remakes of its animated classics and is himself attached to The Lion King and Jungle Book 2.", 
            pic:"https://images-na.ssl-images-amazon.com/images/M/MV5BMzE0NzgyODIxN15BMl5BanBnXkFtZTgwNDU0NjU5NzE@._V1_UY666_CR262,0,666,666_AL_.jpg",
            pic2:"http://cdn3.thr.com/sites/default/files/2016/01/the_jungle_book_poster_key_art.jpg",
            pic3:"http://www.trbimg.com/img-5713b773/turbine/la-et-ct-the-jungle-book-box-office-20160417"},
            {id: 7, 
            rank: "#7",
            name: "The Magnificent Seven",  
            info: "The line-up certainly was magnificent for this Western remake of the 1960 classic (itself a remake of 1954’s Seven Samurai). Denzel Washington, Chris Pratt and Ethan Hawke were among those that brought grit, comedy and action, while director Antoine Fuqua delivered a violent but ultimately satisfying take on good versus evil in the Wild West.",  
            pic:"https://images-na.ssl-images-amazon.com/images/M/MV5BMTc0ODc5NTYxN15BMl5BanBnXkFtZTgwNzk5OTc3MDI@._V1_UY666_CR111,0,666,666_AL_.jpg",
            pic2:"http://www.sonypictures.com/movies/themagnificentseven/assets/images/onesheet.jpg",
            pic3:"https://resizing.flixster.com/GLZaLCKdEmHGlrf3zhBxi7dhkG4=/300x300/v1.bjsxMDg2NDU1O2o7MTc0Mjc7MTIwMDszMDAwOzE4OTQ"},
            {id: 8, 
            rank: "#8",
            name: "Ghostbusters",  
            info: "The team behind Bridesmaids, the best of Saturday Night Live, and the support of the original Ghostbusters made this one of the most popular movies of the year. While this all-female reboot of the classic 1984 comedy did suffer from a polarizing internet backlash, it went on to take nearly $230 million at the global box office.",  
            pic:"https://images-na.ssl-images-amazon.com/images/M/MV5BMjA1MDIzNTA5NV5BMl5BanBnXkFtZTgwNzYyODk0NzE@._V1_UY666_CR166,0,666,666_AL_.jpg",
            pic2:"https://number48productions.files.wordpress.com/2016/07/ghostbusters-2016.jpg",
            pic3:"http://1428elm.com/files/2016/07/gb-cast.jpg"},
            {id: 9, 
            rank: "#9",
            name: "Warcraft: The Beginning",  
            info: "Warcraft joins a long list of video games that struggled when making the leap to the big screen, even with the presence of Vikings star Travis Fimmel. But it did raise the bar in motion-capture technology, delivering a jaw-dropping fantasy world of Orcs and magic, and surpassed Prince of Persia: The Sands of Time as the highest-grossing video game adaptation of all time.",  
            pic:"https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxNjQ4NTQ3OV5BMl5BanBnXkFtZTgwNTI5NDEyNzE@._V1_UY666_CR468,0,666,666_AL_.jpg",
            pic2:"https://pbs.twimg.com/media/CtS7mkLWYAAtCBS.jpg",
            pic3:"http://www.indiewire.com/wp-content/uploads/2016/06/warcraft-movie-anduin-and-orcs.jpg"},
            {id: 10, 
            rank: "#10",
            name: "The Legend of Tarzan",  
            info: "The classic character swung back onto movie screens with Alexander Skarsgård as the king of the swingers and Christoph Waltz as the scenery-chewing villain. But it was IMDb’s top star of 2016, Margot Robbie, who proved the star of the show and showed that Tarzan’s Jane could be more than just a damsel in distress.",  
            pic:"https://images-na.ssl-images-amazon.com/images/M/MV5BMTg5NjA1NDg1NV5BMl5BanBnXkFtZTgwMzg4OTQ0NzE@._V1_UY666_CR144,0,666,666_AL_.jpg",
            pic2:"https://i.ytimg.com/vi/Aj7ty6sViiU/maxresdefault.jpg",
            pic3:"http://www.newdvdreleasedates.com/images/posters/large/the-legend-of-tarzan-2016-03.jpg"},
        ];

        var id = $stateParams["id"];

        this.detail = details.filter(d => d.id == id)[0];
    }

}